//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.06 at 05:39:10 PM SGT 
//


package com.cir.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for citation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="citation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authors" type="{}authorsType"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="booktitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="journal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contexts" type="{}contextsType" minOccurs="0"/>
 *         &lt;element name="marker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rawString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "citation", propOrder = {
    "authors",
    "title",
    "date",
    "note",
    "tech",
    "Institution",
    "booktitle",
    "pages",
    "editors",
    "location",
    "journal",
    "volume",
    "issue",
    "publisher",
    "contexts",
    "marker",
    "rawString"
})
public class Citation {

    @XmlElement(required = true)
    protected Authors authors;
    @XmlElement(required = true)
    protected String title;
    protected short date;
    protected String note;
    protected String tech;
    protected String Institution;
    @XmlElement(required = true)
    protected String booktitle;
    protected String pages;
    protected String editors;
    protected String location;
    protected String journal;
    protected Short volume;
    protected Short issue;
    protected String publisher;
    protected Contexts contexts;
    @XmlElement(required = true)
    protected String marker;
    @XmlElement(required = true)
    protected String rawString;
    @XmlAttribute(name = "valid")
    protected boolean valid;

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link Authors }
     *     
     */
    public Authors getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authors }
     *     
     */
    public void setAuthors(Authors value) {
        this.authors = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the date property.
     * 
     */
    public short getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     */
    public void setDate(short value) {
        this.date = value;
    }

    /**
     * Gets the value of the note property.
     * 
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the tech property.
     * 
     */
    public String getTech() {
        return tech;
    }

    /**
     * Sets the value of the tech property.
     * 
     */
    public void setTech(String value) {
        this.tech = value;
    }
    
    /**
     * Gets the value of the institution property.
     * 
     */
    public String getInstitution() {
        return Institution;
    }

    /**
     * Sets the value of the institution property.
     * 
     */
    public void setInstitution(String value) {
        this.Institution = value;
    }

    /**
     * Gets the value of the booktitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBooktitle() {
        return booktitle;
    }

    /**
     * Sets the value of the booktitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBooktitle(String value) {
        this.booktitle = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRawPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRawPages(String value) {
        this.pages = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditors() {
        return editors;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditors(String value) {
        this.editors = value;
    }
    
    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the journal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournal() {
        return journal;
    }

    /**
     * Sets the value of the journal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournal(String value) {
        this.journal = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setVolume(Short value) {
        this.volume = value;
    }
    
    /**
     * Gets the value of the issue property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getIssue() {
        return issue;
    }

    /**
     * Sets the value of the issue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setIssue(Short value) {
        this.issue = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisher(String value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the contexts property.
     * 
     * @return
     *     possible object is
     *     {@link Contexts }
     *     
     */
    public Contexts getContexts() {
        return contexts;
    }

    /**
     * Sets the value of the contexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contexts }
     *     
     */
    public void setContexts(Contexts value) {
        this.contexts = value;
    }

    /**
     * Gets the value of the marker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarker() {
        return marker;
    }

    /**
     * Sets the value of the marker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarker(String value) {
        this.marker = value;
    }

    /**
     * Gets the value of the rawString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRawString() {
        return rawString;
    }

    /**
     * Sets the value of the rawString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRawString(String value) {
        this.rawString = value;
    }

    /**
     * Gets the value of the valid property.
     * 
     * @return
     *     possible object is
     *     {@link boolean }
     *     
     */
    public boolean getValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     * @param value
     *     allowed object is
     *     {@link boolean }
     *     
     */
    public void setValid(boolean value) {
        this.valid = value;
    }
    
    @Override
    public boolean equals(Object o) {
        if (o instanceof Citation) {
          Citation c = (Citation) o;
          int identifier = this.hashCode();
          int toCompare = c.hashCode();
          if (identifier == toCompare) {
              return true; 
          }
        }
        return false;
    }

    @Override
    public int hashCode() {
        String identifier;
        if (this.title != null) {
            identifier = this.marker + this.title.toLowerCase();
        } else if (this.booktitle != null){
            identifier = this.marker + this.booktitle.toLowerCase();
        } else {
            identifier = this.rawString.toLowerCase();
        }
        return identifier.hashCode();
    }
}
