//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 06:05:06 PM SGT 
//


package com.cir.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}authors"/>
 *         &lt;element ref="{}title"/>
 *         &lt;element ref="{}institution"/>
 *         &lt;element ref="{}date"/>
 *         &lt;element ref="{}location"/>
 *         &lt;element ref="{}pages"/>
 *         &lt;element ref="{}booktitle"/>
 *         &lt;element ref="{}journal"/>
 *         &lt;element ref="{}marker"/>
 *         &lt;element ref="{}rawString"/>
 *         &lt;element ref="{}publisher"/>
 *         &lt;element ref="{}tech"/>
 *       &lt;/choice>
 *       &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authorsOrTitleOrInstitution"
})
@XmlRootElement(name = "citation")
public class Citation {

    @XmlElementRefs({
        @XmlElementRef(name = "institution", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "authors", type = Authors.class, required = false),
        @XmlElementRef(name = "marker", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rawString", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "date", type = Date.class, required = false),
        @XmlElementRef(name = "title", type = Title.class, required = false),
        @XmlElementRef(name = "booktitle", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "publisher", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tech", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pages", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "location", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "journal", type = JAXBElement.class, required = false)
    })
    protected List<Object> authorsOrTitleOrInstitution;
    @XmlAttribute(name = "valid")
    protected String valid;

    /**
     * Gets the value of the authorsOrTitleOrInstitution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorsOrTitleOrInstitution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorsOrTitleOrInstitution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Authors }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Date }
     * {@link Title }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getAuthorsOrTitleOrInstitution() {
        if (authorsOrTitleOrInstitution == null) {
            authorsOrTitleOrInstitution = new ArrayList<Object>();
        }
        return this.authorsOrTitleOrInstitution;
    }

    /**
     * Gets the value of the valid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValid(String value) {
        this.valid = value;
    }

}
