//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.06 at 05:39:10 PM SGT 
//


package com.cir.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for context complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="context">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="citStr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startWordPosition" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="endWordPosition" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "context", propOrder = {
    "value"
})
public class Context {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "position")
    protected Short position;
    @XmlAttribute(name = "citStr")
    protected String citStr;
    @XmlAttribute(name = "startWordPosition")
    protected Short startWordPosition;
    @XmlAttribute(name = "endWordPosition")
    protected Short endWordPosition;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPosition(Short value) {
        this.position = value;
    }

    /**
     * Gets the value of the citStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitStr() {
        return citStr;
    }

    /**
     * Sets the value of the citStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitStr(String value) {
        this.citStr = value;
    }

    /**
     * Gets the value of the startWordPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getStartWordPosition() {
        return startWordPosition;
    }

    /**
     * Sets the value of the startWordPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setStartWordPosition(Short value) {
        this.startWordPosition = value;
    }

    /**
     * Gets the value of the endWordPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getEndWordPosition() {
        return endWordPosition;
    }

    /**
     * Sets the value of the endWordPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setEndWordPosition(Short value) {
        this.endWordPosition = value;
    }

}
