//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.06 at 05:39:10 PM SGT 
//


package com.cir.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for variant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="variant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="title" type="{}titleType"/>
 *         &lt;element name="author" type="{}authorType"/>
 *         &lt;element name="affiliation" type="{}affiliationType"/>
 *         &lt;element name="email" type="{}emailType"/>
 *         &lt;element name="sectionHeader" type="{}sectionHeaderType"/>
 *         &lt;element name="bodyText" type="{}bodyTextType"/>
 *         &lt;element name="page" type="{}pageType"/>
 *         &lt;element name="note" type="{}noteType"/>
 *         &lt;element name="figureCaption" type="{}figureCaptionType"/>
 *         &lt;element name="listItem" type="{}listItemType"/>
 *         &lt;element name="equation" type="{}equationType"/>
 *         &lt;element name="figure" type="{}figureType"/>
 *         &lt;element name="subsectionHeader" type="{}subsectionHeaderType"/>
 *         &lt;element name="footnote" type="{}footnoteType"/>
 *         &lt;element name="tableCaption" type="{}tableCaptionType"/>
 *         &lt;element name="table" type="{}tableType"/>
 *         &lt;element name="reference" type="{}referenceType"/>
 *         &lt;element name="abstract" type="{}abstractType"/>
 *       &lt;/choice>
 *       &lt;attribute name="no" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="confidence" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "variant", propOrder = {
    "titleOrAuthorOrAffiliation"
})
public class Variant {

    @XmlElements({
        @XmlElement(name = "title", type = Title.class),
        @XmlElement(name = "author", type = Author.class),
        @XmlElement(name = "affiliation", type = Affiliation.class),
        @XmlElement(name = "email", type = Email.class),
        @XmlElement(name = "sectionHeader", type = SectionHeader.class),
        @XmlElement(name = "bodyText", type = BodyText.class),
        @XmlElement(name = "page", type = Page.class),
        @XmlElement(name = "note", type = Note.class),
        @XmlElement(name = "figureCaption", type = FigureCaption.class),
        @XmlElement(name = "listItem", type = ListItem.class),
        @XmlElement(name = "equation", type = Equation.class),
        @XmlElement(name = "figure", type = Figure.class),
        @XmlElement(name = "subsectionHeader", type = SubsectionHeader.class),
        @XmlElement(name = "footnote", type = Footnote.class),
        @XmlElement(name = "tableCaption", type = TableCaption.class),
        @XmlElement(name = "table", type = Table.class),
        @XmlElement(name = "reference", type = Reference.class),
        @XmlElement(name = "abstract", type = Abstract.class)
    })
    protected List<Object> titleOrAuthorOrAffiliation;
    @XmlAttribute(name = "no")
    protected Byte no;
    @XmlAttribute(name = "confidence")
    protected Float confidence;

    /**
     * Gets the value of the titleOrAuthorOrAffiliation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleOrAuthorOrAffiliation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleOrAuthorOrAffiliation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Title }
     * {@link Author }
     * {@link Affiliation }
     * {@link Email }
     * {@link SectionHeader }
     * {@link BodyText }
     * {@link Page }
     * {@link Note }
     * {@link FigureCaption }
     * {@link ListItem }
     * {@link Equation }
     * {@link Figure }
     * {@link SubsectionHeader }
     * {@link Footnote }
     * {@link TableCaption }
     * {@link Table }
     * {@link Reference }
     * {@link Abstract }
     * 
     * 
     */
    public List<Object> getTitleOrAuthorOrAffiliation() {
        if (titleOrAuthorOrAffiliation == null) {
            titleOrAuthorOrAffiliation = new ArrayList<Object>();
        }
        return this.titleOrAuthorOrAffiliation;
    }

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setNo(Byte value) {
        this.no = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setConfidence(Float value) {
        this.confidence = value;
    }

}
